<a href="https://colab.research.google.com/github/Kgs-Mathaba/TensorFlow_DC_ZTM/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we are going to cover some of the fundamental concepts of tensors using tensorflow

We are covering
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and numpy
* Using @tf.function (a way t speed up regular Python functions)
* Exercises

# Introduction to Tensors

In [2]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [6]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
# Check the number of dimensions (ndim)
scalar.ndim

0

In [8]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [10]:
#check the dimension of the vector
vector.ndim

1

In [12]:
#create matric
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [13]:
matrix.ndim

2