<a href="https://colab.research.google.com/github/Kgs-Mathaba/TensorFlow_DC_ZTM/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we are going to cover some of the fundamental concepts of tensors using tensorflow

We are covering
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and numpy
* Using @tf.function (a way t speed up regular Python functions)
* Exercises

# Introduction to Tensors

In [38]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [39]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [40]:
# Check the number of dimensions (ndim)
scalar.ndim

0

In [41]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [42]:
#check the dimension of the vector
vector.ndim

1

In [43]:
#create matric
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [44]:
matrix.ndim

2

In [45]:
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16) #specify the data type with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [46]:
another_matrix.ndim

2

In [47]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [48]:
tensor.ndim

3

## create tensor with tf.variable

In [49]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7]) 
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [50]:
# change one of the elements in changeable tensor
changeable_tensor[0]=7
changeable_tensor

TypeError: ignored

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
unchangeable_tensor[0].assign(7)

In [ ]:
unchangeable_tensor[0]=7

## Random Tensors

In [ ]:
random_1 = tf.random.Generator.from_seed(42) # seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

In [ ]:
tf.random.uniform(shape=[2])

In [ ]:
random_2 = tf.random.Generator.from_seed(41)
random_2 = random_2.normal(shape=(3,2))
random_2

In [ ]:
random_1 == random_2

In [ ]:
# Shuffle elements in tensor
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim

In [ ]:
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.shuffle(not_shuffled, seed=42) #operational seed

In [ ]:
tf.random.set_seed(42) #global seed


In [ ]:
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

In [51]:
tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b



@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b


print(f())
print(g())

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)


In [52]:


@tf.function
def f():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b



@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b


print(f())
print(g())

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)


In [53]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

# Other ways to make tensors

In [54]:
tf.ones(shape=(2,5), dtype=tf.float32)

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [55]:
tf.zeros(shape=(2,5), dtype=tf.float32)

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

# numpy arrays to tensors

tensors run much faster on GPU computing

In [56]:
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [57]:
tf.constant(numpy_A)

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [58]:
A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [59]:
B = tf.constant(numpy_A, shape=(4,3,2))
B

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

# Information from tensors

In [60]:
B.shape

TensorShape([4, 3, 2])

In [61]:
B.rank()

AttributeError: ignored

In [ ]:
# create rank 4 tensor
rank_4_tensor

In [ ]:
rank_4_tensor[0,0]

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
# tensor attributes
print("datatype of every element:", rank_4_tensor.dtype)
print("Number of dim(rank):", rank_4_tensor.ndim)
print("elements along the 0 axis::" ,rank_4_tensor.shape[0])
print("elements along the last axis:",rank_4_tensor.shape[-1] )
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("shape of tensor:", tf.shape(rank_4_tensor))
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())


In [ ]:
tf.size()

# Indexing tensors

Similar to python lists 

In [ ]:
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
some_list = [1,2,3,4]
some_list[2]

In [ ]:
#Get each the 1st element from each dimension
rank_4_tensor[:1,:1,:1,:1]

In [ ]:
rank_4_tensor[:1,:1,:,:1]

In [ ]:
np.squeeze(rank_4_tensor[:1,:1,:,:1])

In [ ]:
rank_4_tensor[:1,:1,:,:1].numpy()

In [ ]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[10,7],
                             [2,3]])
rank_2_tensor

In [ ]:
rank_2_tensor[:, -1]

In [ ]:
# add in extra dim
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1) # -1 =final axis

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0) 

# Tensor Operations (Manipulation)

In [ ]:
tensor = tf.constant([[10,7],[3,4]])

In [ ]:
tensor+10

In [ ]:
tensor

In [ ]:
tensor * 10

In [ ]:
tensor-23

In [ ]:
tf.multiply(tensor, tensor)

# Matrix Multiplication

In [ ]:
tf.matmul(tensor, tensor)

In [ ]:
# can also use "@"
tensor @ tensor

In [ ]:
# Tensor of shape=(3,2)
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
X

In [ ]:
# tensor of shape = (3,2)
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
Y

In [ ]:
tf.matmul(X,Y, transpose_b=True)

In [ ]:
tf.matmul(X,Y, transpose_a=True)

In [ ]:
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

In [ ]:
tf.tensordot(X,tf.transpose(X), axis=1)

In [ ]:
Y_transpose = tf.transpose(Y)
Y_transpose

In [ ]:
tf.tensordot(X,Y_transpose, axes=1)

In [ ]:
tf.matmul(X, Y_transpose)

In [ ]:
Y_reshape = tf.reshape(Y, shape=(2,3))
Y_reshape

In [ ]:
Y

In [ ]:
tf.tensordot(X, Y_reshape, axes=1)

# Tensor Dtypes

In [ ]:
B = tf.constant([1.7, 7.4])
B.dtype

In [ ]:
C = tf.constant([7,10])
C.dtype

In [ ]:
D = tf.cast(B, dtype = tf.float16)
D, D.dtype

In [ ]:
E = tf.cast(C, dtype=tf.float32)
C.dtype, E, E.dtype

# Aggregating tensors

Condensing tensors to smaller number of elements

In [ ]:
D = tf.constant([-7,-10])
D

In [ ]:
tf.abs(D)

In [ ]:
tf.minimum(D,E)

In [ ]:
E = tf.constant(np.random.randint(0,100, size=50))
E

In [ ]:
tf.size(E), E.shape, E.ndim

In [ ]:
tf.reduce_min(E)

In [ ]:
tf.reduce_max(E)

In [ ]:
tf.reduce_min(E)

In [ ]:
tf.reduce_sum(E)

In [ ]:
tf.reduce

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

In [ ]:
tfp.stats.stddev(B)

In [ ]:
# Find the variance
tf.math.reduce_variance(tf.cast(E, tf.float32))

Find position of max and min

In [ ]:
F = tf.random.uniform(shape=[50])
F

In [ ]:
tf.math.argmax(F)

In [ ]:
F[42]

In [ ]:
tf.math.argmin(F)

In [ ]:
F[tf.math.argmin(F)]

# One hot Encoding

In [ ]:
# list of indices
some_list = [0,1,2,3] # red, green, blue, puple
depth=4

In [ ]:
tf.one_hot(some_list, depth=4)

In [ ]:
tf.one_hot(some_list, depth=4, on_value="Yebo", off_value="Haibo")

In [ ]:
indices = [0,1,2]
depth = 3
tf.one_hot(indices, depth)

In [ ]:
H = tf.range(1,10)
H

In [ ]:
tf.square(H)

In [ ]:
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

In [ ]:
tf.math.log(tf.cast(H, dtype=tf.float32))

# TensorFlow and Numpy

In [ ]:
# Create tensor form np.array
J = tf.constant(np.array([2,3,4,5]))
J

In [ ]:
np.array(J)

In [ ]:
type(np.array(J))

In [ ]:
J.numpy(), type(J.numpy())

In [ ]:
numpy_J = tf.constant(np.array([3,4,5,6]))
tensor_J = tf.constant([3.,7.,8.,9.])
numpy_J.dtype, tensor_J.dtype

#Tensors can be run much faster on GPU or TPU

In [62]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [64]:
!nvidia-smi

Thu May 27 22:56:38 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P0    27W /  70W |    224MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------